version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - test -f backend/requirements.txt && echo "requirements.txt found" || echo "WARNING requirements.txt not found"
  build:
    commands:
      - echo "Build phase - No build needed for vanilla JavaScript frontend"
      - echo "Build completed on $(date)"
  post_build:
    commands:
      - echo "Post build phase completed"

artifacts:
  files:
    - '**/*'
  name: first-launch-artifacts
