name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ 1. Checkout Code
      uses: actions/checkout@v4

    # === DEPLOY FRONTEND STATIC FILES ===
    - name: ✅ 2. Upload Frontend to EC2 (Static Files)
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "frontend/."
        target: "/var/www/html"
        strip_components: 1

    # === DEPLOY BACKEND ===
    - name: ✅ 3. Upload Backend Files to EC2
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "backend/."
        target: "/var/www/first-launch/backend"
        strip_components: 1

    # === RESTART BACKEND AND NGINX ===
    - name: ✅ 4. Backend Setup and Service Restart
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "✅ Deployment Started on Server"

          cd /var/www/first-launch/backend

          # Write backend .env file from GitHub Secret
          echo "${{ secrets.DOT_ENV_BACKEND }}" > .env

          # Create virtual environment if missing
          if [ ! -d "venv" ]; then
            echo "Creating virtual environment..."
            python3 -m venv venv
          fi

          # Install requirements
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate

          # Restart FastAPI backend service
          sudo systemctl daemon-reload
          sudo systemctl restart first-launch

          # Restart Nginx for frontend static update
          sudo systemctl restart nginx

          echo "✅ Deployment Successful!"
